export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
export const LOAD_WEATHER_SUCCESS = 'LOAD_WEATHER_SUCCESS';
export const CHANGE_WEATHER_SUCCESS = 'CHANGE_WEATHER_SUCCESS';